version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app/frontend
      - /usr/app/frontend/node_modules

  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/app/frontend
      - /usr/app/frontend/node_modules
    command: ["npm", "run", "test"]
